
- name: Create empty file with 10MB
  command: dd if=/dev/zero of=/{{file_name}} bs=1M count=10

- name: Format file as ext4 filesystem
  command: mkfs.ext4 /{{file_name}}

- name: Create mount point
  file:
    path: "{{mount_path}}"
    state: directory ##create a /var/www repository

- name: Mount filesystem on /var/www
  command: mount -o loop /{{file_name}} /var/www

##mount to /var.log.apache2
- name: Create the apache2 log folder
  file:
    path: "{{apache_log_folder}}"
    state: directory ##create a /var/www repository

- name: Mount filesystem on /var/www
  command: mount -o loop /{{file_name}} /var/log/apache2